apiVersion: v1
kind: Service
metadata:
  name: my-new-angular-app
  labels:
    app: my-new-angular-app
    role: $COLOR
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-new-angular-app
    role: $COLOR
